### ISSUE TITLE
ENOENT spawn /usr/src/app/node_modules/node-7z-forall/binaries/linux/7za

### ISSUE THREAD

**Issue by koerhunt** [techno-express/node-7z-forall#12]
When I try to extract file with the extractFull method I got ERR
The library is not installing the linux binaries on the /node_modules/node-7z-forall/binaries/linux
I have to link to system binary and install manually.

Error detail:
path:   '/usr/src/app/node_modules/node-7z-forall/binaries/linux/7za',  
spawnargs:   [ 'x',     './files/MyFile.7z',     '-o./files',     '-ssc',     '-y',     '-bb2' ] }","timestamp":"2020-12-03T19:58:47.533Z","type":"err","process_id":0,"app_name":"index"}

SO: Linux 3b72f63d8e35 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

TMP solution:  
mkdr -p /usr/src/app/node_modules/node-7z-forall/binaries/linux
ln -s /usr/bin/7za

**Comment by techno-express** [comment]
Not sure of your setup, if that was the case then GitHub Actions test run at https://github.com/techno-express/node-7z-forall/runs/1495249745?check_suite_focus=true#step:5:123 would be a failed test.

The project is setup to download binaries in, and place within project structure. Your solution means host installed already. Not sure how/where you running `npm install` from. 

Try creating new directory and run `npm install node-7z-forall`
